### ISSUE TITLE
Document or defer the formatAfterPaste option

### ISSUE THREAD

**Issue by evanwarner** [stef-levesque/vscode-multiclip#12]
You should add the `formatAfterPaste` config option to the README. I have `editor.formatOnPaste` turned off and couldn't figure out why formatters were still getting triggered.

Or maybe your option should defer to the `editor.formatOnPaste` setting, and only act if that setting is `true`.

**Comment by MarkSMT** [comment]
Yeah, this messes up the awesome prettier extension as well, i am disabling this extension until this gets fixed!

**Comment by evanwarner** [comment]
@MarkSMT You can just set `"multiclip.formatAfterPaste": false` for the time being!

**Comment by MarkSMT** [comment]
@evanwarner Thx!

**Comment by stef-levesque** [comment]
`multiclip.formatAfterPaste` will be disabled by default, for now.
I may revisit replicating `editor.formatOnPaste` later.
