### ISSUE TITLE
Unable to uninstall the extension

### ISSUE THREAD

**Issue by ivanstefanov** [stef-levesque/vscode-multiclip#13]
Don't know if this is Visual Studio Code or extension error, but I can not uninstall it.
When pressing on Uninstall button the extension seems removed and then when I restart Visual Studio Code again, it is there again.
I don't receive any errors into Developer Console during the uninstalling process

**Comment by stef-levesque** [comment]
That is very strange... Can you try that:
1. Can you open the command palette and select `Open Extensions Folder`
2. Look for any folder named `slevesque.vscode-multiclip*`
3. Remove and Reload

**Comment by ivanstefanov** [comment]
Thank you @stef-levesque . I managed to fix the issue. I just needed to close all tabs of Visual Studio Code, to close the editor itself, then to open it again and to do the uninstall. Maybe it doesn't kill all running instances of the plugin on deletion process.

**Comment by stef-levesque** [comment]
Hm, good to know. Thanks.
