### ISSUE TITLE
Copied C# code from Visual Studio 2017 loses formatting when pasted into .HTML file

### ISSUE THREAD

**Issue by MikeTheGreat** [stef-levesque/vscode-multiclip#14]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
githistory|don|0.2.3
python|don|0.7.0
auto-close-tag|for|0.4.3
RelativePath|jak|1.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
font-awesome-codes-html|med|0.0.7
csharp|ms-|1.12.1
view-in-browser|qin|0.0.5
startanyshell|rem|0.3.1
vscode-multiclip|sle|0.1.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Install and activate "Multiple clipboards for VSCode"
2. Copy C# source code from Visual Studio 2017 (sample included below)
3. Past into .HTML file

**Example code to copy-n-paste:**
```
            Console.WriteLine("This is printed verbatim (exactly as written here)");
            int number;
            number = 10;
            Console.WriteLine(number);
            Console.WriteLine("Number is: " + number);
```

Reproduces with "Multiple clipboards for VSCode" extension enabled: Yes
Reproduces without "Multiple clipboards for VSCode" extension enabled: No

**Comment by stef-levesque** [comment]
The formating changed in vscode.
Try to add the following in your User Settings, and reload the editor.
```javascript
"multiclip.formatAfterPaste": false,
```

**Comment by MikeTheGreat** [comment]
Putting that into my User Settings (and reloading the editor) does fix the problem.  Thanks!
