### ISSUE TITLE
Keyboard Shift+Alt+v clashes with AltGr key.

### ISSUE THREAD

**Issue by mickeypearce** [stef-levesque/vscode-multiclip#17]
I have a problem typing @ character (AltGr + @) as it now fires "Select clipboard to paste" (Shift+Alt+v). "@" is on the same key as "v" on my keybord.

I think this is the case: https://developercommunity.visualstudio.com/content/problem/38472/visual-studio-keyboard-shortcuts-clashes-with-the.html.

**Comment by stef-levesque** [comment]
@alexandrudima  This seems related to https://github.com/Microsoft/vscode/issues/50341 
Could you confirm if this is a VSCode, Monaco, or Chromium issue?
Is there anything I can do to fix it on the Extension side?

**Comment by alexandrudima** [comment]
@stef-levesque The recommendation is to never use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+ keybindings on Windows, as they might prevent character input in certain keyboard layouts.

The resolution is to use a different default keybinding or perhaps none at all and simply let the end-users configure keybindings.
