### ISSUE TITLE
Set own shortcut

### ISSUE THREAD

**Issue by Morgy93** [stef-levesque/vscode-multiclip#2]
Is it possible somehow to change the shortcut for this feature?
I'd like to press `ctrl+shift+v` rather than `ctrl+alt+v`.
Probably I just need to know the parameters for the keybindings.json

``` 
{
	"key": "ctrl+shift+v", 
	"command": "???", 
	"when": "???" 
}
```

**Comment by stef-levesque** [comment]
The shortcut can be found in [package.json](https://github.com/stef-levesque/vscode-multiclip/blob/master/package.json)

```
{
	"key": "alt+ctrl+v",
	"mac": "alt+cmd+v",
	"command": "multiclip.paste",
	"when": "editorTextFocus"
}
```

`ctrl+shift+v` is already used by Code for `workbench.action.markdown.togglePreview`

**Comment by rafaelbiten** [comment]
Sorry for reopening this issue but the command "shift+cmd+x" is also conflicting with the view extensions command. How can this be fixed?

`{ "key": "shift+cmd+x",           "command": "workbench.view.extensions" }`

The only command I really need is the cmd+alt+v (when I'm prompted to pick what I want to paste) so, how can I disable the other shortcuts without editing the package.json?

And thanks for this great extension! I'm trying to transition from Sublime and this is something that I use quite a lot!

**Comment by rafaelbiten** [comment]
nvm! Pasting the following line on my `keybindings.json` file did the trick:

`{"key": "shift+cmd+x", "command": "workbench.view.extensions"}`

This overwrites the plugins' shortcut. Tks again!
