### ISSUE TITLE
Cycle through clipboard items

### ISSUE THREAD

**Issue by Morgy93** [stef-levesque/vscode-multiclip#3]
Would it be possible somehow to just cycle through the items while using this feature to paste items?
Like I got three items in the clipboard and `ctrl+alt+v` directly pastes the first item - pressing it again will then paste the second item instead and so on.
This would make using it a little faster. :)

**Comment by stef-levesque** [comment]
A new command to paste-and-cycle have just been added.
Try updating to vscode-multiclip@0.0.4 and use `ctrl+shift+v`
