### ISSUE TITLE
Multiclip paste doesn't show up on macOS

### ISSUE THREAD

**Issue by iprotsyuk** [stef-levesque/vscode-multiclip#32]
The title basically describes it: I don't get any errors nor do I have any installation issues, but when I press `multiclip.paste` combination (Cmd+Shift+V) nothing happens.

VS Code "About" output:

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by boggonpi** [comment]
I had to add the shortcut.
1. Look for 'Multiclip List Buffer' in VS Code Keyboard Shortcuts.
2. Or go into keybindings.json and add:
{
        "key": "ctrl+alt+v",
        "command": "multiclip.list",
        "when": "editorTextFocus"
}

the 'editorTextFocus' prevents the shortcut from triggering when you're not in an editor.

**Comment by iprotsyuk** [comment]
Yay, worked for me :)
Thank you so much!
