### ISSUE TITLE
please do not overridden the default shortcut.

### ISSUE THREAD

**Issue by iulo** [stef-levesque/vscode-multiclip#7]
you can give a suggestion for users how to set the shortcut by themselves.

**Comment by stef-levesque** [comment]
I'm trying to be as little invasive as possible, but I can't build a clipboard history without overriding `copy` and `cut` shortcuts. As for `paste`, the behaviour should be completely transparent as `multiclip.formatAfterPaste` is now disabled by default (VSCode does a better job now)

Could you explain what problem it is causing ?

**Comment by mickeypearce** [comment]
I have a problem with typing @ character (AltGr + @) as it now fires "Select clipboard to paste". 
I think this is the case: https://developercommunity.visualstudio.com/content/problem/38472/visual-studio-keyboard-shortcuts-clashes-with-the.html.
