### ISSUE TITLE
Changed default shortcuts to SHIFT + INSERT / CTRL + INSERT

### ISSUE THREAD

**Issue by johnnyPescarul** [stef-levesque/vscode-multiclip#8]
Not sure what keys I pressed, but for some reason the extension shortcuts changed from the default Ctrl + C/ Ctrl + V to  to SHIFT + INSERT / CTRL + INSERT. Restarting VS Code, disabling/re-enabling the extension does not fix the issue.

**Comment by stef-levesque** [comment]
`Shift+Insert` / `Ctrl+Insert` are other ways to copy/paste in Windows.

The extension only override `Ctrl+X`, `Ctrl+C` and `Ctrl+V` (see package.json) 

You can override yourself by going to `Preferences: Open Keyboard Shortcuts (Ctrl+K, Ctrl+S)`

**Comment by johnnyPescarul** [comment]
The problem is that Ctr+C/Ctr+V no longer works. These shortcuts are disabled by the extension. I understand that there are other shortcuts for copy/paste, but the extension should not prevent you from using the default Ctr+C/Ctr+V. It should not disable them.
